server:
  port: 7001

spring:
  application:
    name: service-consumer
dubbo:
  application:
    name: service-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    subscribe: true
  protocol:
    name: dubbo
    serialization: kryo
    accesslog: true
  monitor:
    protocol: registry
  consumer:
    timeout: 1000
    check: false #检查所调用的提供者服务是否可用
    retries: 2

