server:
  port: 7001

spring:
  application:
    name: service-consumer
  redis:
    port: 6379
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 200 #连接池最大连接数
        max-wait: -1 #连接池最大阻塞等待时间
        min-idle: 0 #连接池中的最小空闲连接
        max-idle: 10 #连接池中的最大空闲连接
    timeout: 1000 #连接超时时间

dubbo:
  application:
    name: service-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    subscribe: true
  protocol:
    name: dubbo
    serialization: kryo
    accesslog: true
  monitor:
    protocol: registry
  consumer:
    timeout: 1000
    check: false #检查所调用的提供者服务是否可用
    retries: 2
